// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgNDNcaX663-ccWypy0h7Kkf92VU4lj3M',
    appId: '1:693757088260:web:f9481474bd9872efbcdb51',
    messagingSenderId: '693757088260',
    projectId: 'deliveryapp-8d0e8',
    authDomain: 'deliveryapp-8d0e8.firebaseapp.com',
    storageBucket: 'deliveryapp-8d0e8.firebasestorage.app',
    measurementId: 'G-ZLB3T7PB2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBztecSbtet7sQFeGW2f5hbj0QVOExa4bI',
    appId: '1:693757088260:android:d5fc7ca33af7a2a0bcdb51',
    messagingSenderId: '693757088260',
    projectId: 'deliveryapp-8d0e8',
    storageBucket: 'deliveryapp-8d0e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrSAJKhrEJX8pSuOLv3UhB_ln32lg-Y5o',
    appId: '1:693757088260:ios:737c43511376f9dcbcdb51',
    messagingSenderId: '693757088260',
    projectId: 'deliveryapp-8d0e8',
    storageBucket: 'deliveryapp-8d0e8.firebasestorage.app',
    iosBundleId: 'com.example.delivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrSAJKhrEJX8pSuOLv3UhB_ln32lg-Y5o',
    appId: '1:693757088260:ios:737c43511376f9dcbcdb51',
    messagingSenderId: '693757088260',
    projectId: 'deliveryapp-8d0e8',
    storageBucket: 'deliveryapp-8d0e8.firebasestorage.app',
    iosBundleId: 'com.example.delivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgNDNcaX663-ccWypy0h7Kkf92VU4lj3M',
    appId: '1:693757088260:web:d56f4c05b19b0990bcdb51',
    messagingSenderId: '693757088260',
    projectId: 'deliveryapp-8d0e8',
    authDomain: 'deliveryapp-8d0e8.firebaseapp.com',
    storageBucket: 'deliveryapp-8d0e8.firebasestorage.app',
    measurementId: 'G-KN135WFPYF',
  );
}
